### ISSUE TITLE
Identity initialization

### ISSUE THREAD

**Issue by bitbin42** [mheydt-simplilearn/netfsdell#1]
I'm not finding anything on how to configure the identity tales in the database. I've tried various things found in google but always end up with 'invalid column NormalizedName' errors.

**Comment by mheydt** [comment]
First, who is this?

**Comment by bitbin42** [comment]
Sorry, Bob Butler from the Dell FSD.Net class

**Comment by mheydt** [comment]
Just wanted to make sure.

You can get me easier with ***@***.***  Wasn't allowed to tell you that
during the course :(

Easiest thing is to create a new asp.net core project that uses
authorization/individual user accounts.  Once that is created, put your
connection string in appconfig.json.  Then open the package manager window
in visual studio and do: Update-Database.  That will create the database.
You can use it in other projects, not just the new one.

**Comment by bitbin42** [comment]
Thanks, I will try that.  Your email did not appear.  You can get me at my name with a dot instead of a space at dell dot com
I did put together my own webapi backend and react frontend but it is crude so I wanted to also get your versions running.

**Comment by mheydt** [comment]
Also,  see:

https://docs.microsoft.com/en-us/aspnet/core/security/authentication/scaffold-identity?view=aspnetcore-5.0&tabs=visual-studio

Thing is that sample project from the wizard has everything you need to
create the db by 1) setting the connectionstring properly and 2) using
Update-Database to run the database migrations created by the wizard.

**Comment by mheydt** [comment]
I think it filtered out that as sensitive info.  I'll email you directly.
